// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailPen.Data;

#nullable disable

namespace RailPen.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230928121646_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RailPen.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRetirement")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PensionReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetRetirementAge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRetirement = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brian",
                            Gender = 0,
                            LastName = "Mccall",
                            PensionReferenceNumber = "P0000097",
                            TargetRetirementAge = 60
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1984, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRetirement = new DateTime(2044, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            Gender = 1,
                            LastName = "Kramer",
                            PensionReferenceNumber = "PO000136",
                            TargetRetirementAge = 60
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1975, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRetirement = new DateTime(2037, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lianne",
                            Gender = 1,
                            LastName = "Barrow",
                            PensionReferenceNumber = "P0004657",
                            TargetRetirementAge = 62
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1980, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRetirement = new DateTime(2045, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Richardson",
                            PensionReferenceNumber = "P0004701",
                            TargetRetirementAge = 65
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRetirement = new DateTime(2057, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kara",
                            Gender = 1,
                            LastName = "Mccall",
                            PensionReferenceNumber = "P0004782",
                            TargetRetirementAge = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
